CREATE DATABASE QLNHATRO_PS31493;
go
drop database QLNHATRO_PS31493
USE QLNHATRO_PS3149;
go
/*
Bảng LOAINHA lưu thông tin loại hình nhà trọ cho thuê 
(Ví dụ: Căn hộ chung cư, Nhà riêng, Phòng trọ khép kín….)
*/
CREATE TABLE LOAINHA (
	MALOAI VARCHAR(5),
	TENLOAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAINHA PRIMARY KEY (MALOAI)
);
GO
/*
Bảng NGUOIDUNG lưu toàn bộ thông tin các thành viên của Website. Những người
dùng này có quyền đăng tin nhà trọ cho thuê, hoặc gửi comment đánh giá chất lượng của 
các nhà trọ được đăng tin.
*/

-- 0: NAM
-- 1: NU

CREATE TABLE NGUOIDUNG (
	MA_ND VARCHAR(5),
	TEN_ND NVARCHAR(50) NOT NULL,
	GIOITINH BIT NOT NULL,
	DIENTHOAI VARCHAR(11),
	DIACHI_ND NVARCHAR(50) NOT NULL,
	QUAN_ND NVARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50),
	CONSTRAINT PK_NGUOIDUNG PRIMARY KEY (MA_ND)
);
GO

/*
Bảng NHATRO lưu thông tin nhà trọ cho thuê
*/

CREATE TABLE NHATRO (
	MA_NT VARCHAR(5),
	DIENTICH FLOAT NOT NULL,
	GIAPHONG MONEY NOT NULL,
	DIACHI_NT NVARCHAR(50) NOT NULL,
	QUAN_NT NVARCHAR(20) NOT NULL,
	MOTA NVARCHAR(200),
	NGAYDANGTIN DATE NOT NULL,
	LOAI VARCHAR(5),
	NG_LIENHE VARCHAR(5),
	CONSTRAINT PK_NHATRO PRIMARY KEY (MA_NT),
	CONSTRAINT CK_DIENTICH CHECK(DIENTICH > 0),
	CONSTRAINT CK_GIAPHONG CHECK(GIAPHONG > 0)
);
GO

/*
Bảng DANHGIA lưu thông tin đánh giá chất lượng nhà trọ
*/
-- 0: DISLIKE
-- 1: LIKE
CREATE TABLE DANHGIA (
	NG_DANHGIA VARCHAR(5),
	MA_TRO VARCHAR(5),
	DANHGIA BIT,
	NOIDUNG NVARCHAR(200),
	CONSTRAINT PK_DANHGIA PRIMARY KEY (NG_DANHGIA,MA_TRO)
);
GO